
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: bakehouse
  type: NodePort
status:
  loadBalancer: {}
